// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package pht

import (
	"github.com/google/wire"
	"pht/comments-processor/pht/auth"
	"pht/comments-processor/pht/config"
	"pht/comments-processor/pht/handlers"
	"pht/comments-processor/repo"
)

// Injectors from wire.go:

func ProvideLocator(pp repo.ParamsProvider) (*Locator, error) {
	tokensProvider := auth.NewTokensProvider(pp)
	configConfig := config.NewConfig(pp)
	tokensRefresher, err := auth.NewTokensRefresher(configConfig, tokensProvider, tokensProvider, tokensProvider)
	if err != nil {
		return nil, err
	}
	locator := NewLocator(tokensProvider, tokensProvider, tokensRefresher)
	return locator, nil
}

func ProvideRouter(l *Locator) (*handlers.Router, error) {
	accessTokenProvider := l.accessTokenProvider
	tokensRefresher := l.tokensRefresher
	router := handlers.NewRouter(accessTokenProvider, tokensRefresher)
	return router, nil
}

// wire.go:

var TokensProviderSet = wire.NewSet(auth.NewTokensProvider, wire.Bind(new(auth.AccessTokenProvider), new(*auth.TokensProvider)), wire.Bind(new(auth.AccessTokenUpdater), new(*auth.TokensProvider)), wire.Bind(new(auth.RefreshTokenProvider), new(*auth.TokensProvider)), wire.Bind(new(auth.RefreshTokenUpdater), new(*auth.TokensProvider)))

var PhtSet = wire.NewSet(
	TokensProviderSet, config.NewConfig, auth.NewTokensRefresher, wire.Bind(new(config.ConfigProvider), new(*config.Config)), NewLocator,
)
